# MLHyperparameterTuning  Pipeline
#
# The following variables must be set within the DevOps portal.
#
# azureSubscription: (str) - Name of the ADO Service Connection. EX: NAME_OF_SUB(XXX-XXX-XXX)
# azure_subscription (guid) - The subscription ID. EX XXXX-XXXX-XXXX
# Github_Repo_Service_Connection (str) - Name of the ADO Service Connection to reach Github.

resources:
  repositories:
    - repository: aitemplates
      type: github
      name: microsoft/AI
      endpoint: $(Github_Repo_Service_Connection)

variables:
  TridentWorkloadType: ai-ml-score-int
  TridentWorkloadTypeShort: aimlscore
  DeployLocation: eastus
  DeploymentName: MLScoreDeployJob
  ProjectLocation: "."
  PythonPath: "."

# In additional to the above variables, the "template" parameter of the last step must also be hard coded for each workload

trigger:
  batch: true
  branches:
    include:
    - mabou/instrument

stages:
- template: .ci/stages/deploy_notebooks_stages.yml@aitemplates
  parameters:
    jobDisplayName: $(DeploymentName)
    TridentWorkloadTypeShort: $(TridentWorkloadTypeShort)
    DeployLocation: $(DeployLocation)
    DefaultWorkingDirectory: $(System.DefaultWorkingDirectory)
    Template: MLTrainDeployAMLJob.yml
    azureSubscription: $(azureSubscription)
    azure_subscription: $(azure_subscription)
    ProjectLocation: $(ProjectLocation)
    PythonPath: $(PythonPath)
