# MLHyperparameterTuning  Pipeline
resources:
  repositories:
    - repository: aitemplates
      type: github
      name: microsoft/AI
      endpoint: AIArchitecturesAndPractices-GitHub

variables:
  CloudPlatform: AzureCloud
  TridentWorkloadType: ai-ml-score-int
  TridentWorkloadTypeShort: aimlscore
  DeployLocation: eastus
  azureSubscription: AG-AzureCAT-AIDevOps-Test-COGSNonProd-IO1685734(0ca618d2-22a8-413a-96d0-0f1b531129c3)
  azure_subscription: 0ca618d2-22a8-413a-96d0-0f1b531129c3
  DeploymentName: MLScoreDeployJob
  ProjectLocation: "."
  PythonPath: "."

# In additional to the above variables, the "template" parameter of the last step must also be hard coded for each workload

trigger:
  batch: true
  branches:
    include:
    - mabou/instrument

stages:
- template: .ci/stages/deploy_notebooks_stage.yml@aitemplates
  parameters:
    stageName: 'stable'
    jobDisplayName: $(DeploymentName)
    TridentWorkloadTypeShort: $(TridentWorkloadTypeShort)
    DeployLocation: $(DeployLocation)
    TestPostfix: "-stable"
    DefaultWorkingDirectory: $(System.DefaultWorkingDirectory)
    Template: MLTrainDeployAMLJob.yml
    azureSubscription: $(azureSubscription)
    azure_subscription: $(azure_subscription)
    ProjectLocation: $(ProjectLocation)
    PythonPath: $(PythonPath)

- template: .ci/stages/deploy_notebooks_stage.yml@aitemplates
  parameters:
    stageName: 'release'
    jobDisplayName: $(DeploymentName)
    TridentWorkloadTypeShort: $(TridentWorkloadTypeShort)
    DeployLocation: $(DeployLocation)
    TestPostfix: "-release"
    DefaultWorkingDirectory: $(System.DefaultWorkingDirectory)
    Template: MLTrainDeployAMLJob.yml
    azureSubscription: $(azureSubscription)
    azure_subscription: $(azure_subscription)
    ProjectLocation: $(ProjectLocation)
    PythonPath: $(PythonPath)
    flighting_release: true

- template: .ci/stages/deploy_notebooks_stage.yml@aitemplates
  parameters:
    stageName: 'preview'
    jobDisplayName: $(DeploymentName)
    TridentWorkloadTypeShort: $(TridentWorkloadTypeShort)
    DeployLocation: $(DeployLocation)
    TestPostfix: "-preview"
    DefaultWorkingDirectory: $(System.DefaultWorkingDirectory)
    Template: MLTrainDeployAMLJob.yml
    azureSubscription: $(azureSubscription)
    azure_subscription: $(azure_subscription)
    ProjectLocation: $(ProjectLocation)
    PythonPath: $(PythonPath)
    flighting_preview: true
